### PR TITLE
css fixes and added sharing

### PR DESCRIPTION
**Pull request by MarcBalaban**

### CODE REVIEW

**Comment by knatsuki** [comment]
+1

**Comment by sungminchang** [comment]
nice, you going to take this reddit viral? Hey, the save button doesn't work anymore in the save modal, we have to check that out.

**Comment by MarcBalaban** [comment]
I'm not sure about viral, but I want to mark the project as 'complete'.  We
never really did finish it.  :)
hmmm, save seems to work on loopjam.in.
If you're running locally, you need to have PostGres running.

**Comment by sungminchang** [comment]
Yeah, had it running, I'll investigate what's wrong. Specifically, is the 'save' button in the modal supposed to stay grey?

**Comment by MarcBalaban** [comment]
Check on loopjam.in and see if save still doesn't work.

**Pull request merged**
